// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {db} from '../models';

export function ConnectToDatabase(arg1:main.Connection):Promise<boolean|string>;

export function DeleteConnection(arg1:string):Promise<void>;

export function DisconnectFromDatabase(arg1:main.Connection):Promise<void>;

export function ExecuteNonQuery(arg1:main.Connection,arg2:string,arg3:string):Promise<number>;

export function ExecuteQuery(arg1:main.Connection,arg2:string,arg3:string):Promise<main.QueryResult>;

export function GetConnections():Promise<Array<main.Connection>>;

export function GetDatabases(arg1:main.Connection):Promise<Array<main.DatabaseInfo>>;

export function GetFunctions(arg1:main.Connection,arg2:string):Promise<Array<main.TableInfo>>;

export function GetLanguage():Promise<string>;

export function GetServerInfo(arg1:main.Connection):Promise<Record<string, string>>;

export function GetSupportedDatabases():Promise<Array<Record<string, string>>>;

export function GetSupportedFeatures():Promise<Record<string, Array<string>>>;

export function GetTableColumns(arg1:main.Connection,arg2:string,arg3:string):Promise<Array<db.ColumnInfo>>;

export function GetTables(arg1:main.Connection,arg2:string):Promise<Array<main.TableInfo>>;

export function GetViews(arg1:main.Connection,arg2:string):Promise<Array<main.TableInfo>>;

export function Greet(arg1:string):Promise<string>;

export function OpenFileDialog(arg1:string,arg2:string):Promise<string>;

export function RunAllTests():Promise<Array<main.TestResult>>;

export function RunConnectionTest(arg1:main.Connection):Promise<main.TestResult>;

export function SaveConnection(arg1:main.Connection):Promise<void>;

export function SaveFileDialog(arg1:string,arg2:string):Promise<string>;

export function SetLanguage(arg1:string):Promise<void>;

export function TestConnection(arg1:main.Connection):Promise<boolean|string>;

export function WindowClose():Promise<void>;

export function WindowIsMaximized():Promise<boolean>;

export function WindowMaximize():Promise<void>;

export function WindowMinimize():Promise<void>;
