// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AnalyzeQuery(arg1) {
  return window['go']['main']['App']['AnalyzeQuery'](arg1);
}

export function AnalyzeTableUsage(arg1, arg2) {
  return window['go']['main']['App']['AnalyzeTableUsage'](arg1, arg2);
}

export function BatchEdit(arg1, arg2) {
  return window['go']['main']['App']['BatchEdit'](arg1, arg2);
}

export function BeautifySQL(arg1) {
  return window['go']['main']['App']['BeautifySQL'](arg1);
}

export function BeginTransaction(arg1, arg2, arg3) {
  return window['go']['main']['App']['BeginTransaction'](arg1, arg2, arg3);
}

export function CommitTransaction(arg1) {
  return window['go']['main']['App']['CommitTransaction'](arg1);
}

export function CompactSQL(arg1) {
  return window['go']['main']['App']['CompactSQL'](arg1);
}

export function CompareQueries(arg1, arg2) {
  return window['go']['main']['App']['CompareQueries'](arg1, arg2);
}

export function CompareTables(arg1, arg2) {
  return window['go']['main']['App']['CompareTables'](arg1, arg2);
}

export function ConnectToDatabase(arg1) {
  return window['go']['main']['App']['ConnectToDatabase'](arg1);
}

export function DeleteConnection(arg1) {
  return window['go']['main']['App']['DeleteConnection'](arg1);
}

export function DisconnectFromDatabase(arg1) {
  return window['go']['main']['App']['DisconnectFromDatabase'](arg1);
}

export function EditTableData(arg1, arg2) {
  return window['go']['main']['App']['EditTableData'](arg1, arg2);
}

export function ExecuteInTransaction(arg1, arg2) {
  return window['go']['main']['App']['ExecuteInTransaction'](arg1, arg2);
}

export function ExecuteMultiQuery(arg1, arg2, arg3) {
  return window['go']['main']['App']['ExecuteMultiQuery'](arg1, arg2, arg3);
}

export function ExecuteMultiQueryWithTimeout(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ExecuteMultiQueryWithTimeout'](arg1, arg2, arg3, arg4);
}

export function ExecuteNonQuery(arg1, arg2, arg3) {
  return window['go']['main']['App']['ExecuteNonQuery'](arg1, arg2, arg3);
}

export function ExecuteQuery(arg1, arg2, arg3) {
  return window['go']['main']['App']['ExecuteQuery'](arg1, arg2, arg3);
}

export function ExecuteQueryWithTimeout(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ExecuteQueryWithTimeout'](arg1, arg2, arg3, arg4);
}

export function ExecuteTransactionBatch(arg1) {
  return window['go']['main']['App']['ExecuteTransactionBatch'](arg1);
}

export function ExportCompareResult(arg1, arg2) {
  return window['go']['main']['App']['ExportCompareResult'](arg1, arg2);
}

export function ExportData(arg1, arg2) {
  return window['go']['main']['App']['ExportData'](arg1, arg2);
}

export function FormatSQL(arg1, arg2) {
  return window['go']['main']['App']['FormatSQL'](arg1, arg2);
}

export function GenerateInsertStatement(arg1, arg2) {
  return window['go']['main']['App']['GenerateInsertStatement'](arg1, arg2);
}

export function GenerateUpdateStatement(arg1, arg2, arg3) {
  return window['go']['main']['App']['GenerateUpdateStatement'](arg1, arg2, arg3);
}

export function GetAutoCompleteSuggestions(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetAutoCompleteSuggestions'](arg1, arg2, arg3, arg4);
}

export function GetCompareReport(arg1) {
  return window['go']['main']['App']['GetCompareReport'](arg1);
}

export function GetConnections() {
  return window['go']['main']['App']['GetConnections']();
}

export function GetDatabases(arg1) {
  return window['go']['main']['App']['GetDatabases'](arg1);
}

export function GetEditableColumns(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetEditableColumns'](arg1, arg2, arg3);
}

export function GetExplainPlan(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetExplainPlan'](arg1, arg2, arg3);
}

export function GetFunctions(arg1, arg2) {
  return window['go']['main']['App']['GetFunctions'](arg1, arg2);
}

export function GetLanguage() {
  return window['go']['main']['App']['GetLanguage']();
}

export function GetQuickSuggestions(arg1) {
  return window['go']['main']['App']['GetQuickSuggestions'](arg1);
}

export function GetSQLStructure(arg1) {
  return window['go']['main']['App']['GetSQLStructure'](arg1);
}

export function GetServerInfo(arg1) {
  return window['go']['main']['App']['GetServerInfo'](arg1);
}

export function GetSlowQueries(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetSlowQueries'](arg1, arg2, arg3);
}

export function GetSupportedDatabases() {
  return window['go']['main']['App']['GetSupportedDatabases']();
}

export function GetSupportedFeatures() {
  return window['go']['main']['App']['GetSupportedFeatures']();
}

export function GetTableColumns(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetTableColumns'](arg1, arg2, arg3);
}

export function GetTableColumnsForAutoComplete(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetTableColumnsForAutoComplete'](arg1, arg2, arg3);
}

export function GetTableForeignKeys(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetTableForeignKeys'](arg1, arg2, arg3);
}

export function GetTableIndexes(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetTableIndexes'](arg1, arg2, arg3);
}

export function GetTableStatistics(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetTableStatistics'](arg1, arg2, arg3);
}

export function GetTableStats(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetTableStats'](arg1, arg2, arg3);
}

export function GetTables(arg1, arg2) {
  return window['go']['main']['App']['GetTables'](arg1, arg2);
}

export function GetViews(arg1, arg2) {
  return window['go']['main']['App']['GetViews'](arg1, arg2);
}

export function ImportData(arg1, arg2) {
  return window['go']['main']['App']['ImportData'](arg1, arg2);
}

export function MinifySQL(arg1) {
  return window['go']['main']['App']['MinifySQL'](arg1);
}

export function OpenFileDialog(arg1, arg2) {
  return window['go']['main']['App']['OpenFileDialog'](arg1, arg2);
}

export function RollbackTransaction(arg1) {
  return window['go']['main']['App']['RollbackTransaction'](arg1);
}

export function RunAllTests() {
  return window['go']['main']['App']['RunAllTests']();
}

export function RunConnectionTest(arg1) {
  return window['go']['main']['App']['RunConnectionTest'](arg1);
}

export function SaveConnection(arg1) {
  return window['go']['main']['App']['SaveConnection'](arg1);
}

export function SaveFileDialog(arg1, arg2) {
  return window['go']['main']['App']['SaveFileDialog'](arg1, arg2);
}

export function SetLanguage(arg1) {
  return window['go']['main']['App']['SetLanguage'](arg1);
}

export function TestConnection(arg1) {
  return window['go']['main']['App']['TestConnection'](arg1);
}

export function ValidateSQL(arg1) {
  return window['go']['main']['App']['ValidateSQL'](arg1);
}

export function WindowClose() {
  return window['go']['main']['App']['WindowClose']();
}

export function WindowIsMaximized() {
  return window['go']['main']['App']['WindowIsMaximized']();
}

export function WindowMaximize() {
  return window['go']['main']['App']['WindowMaximize']();
}

export function WindowMinimize() {
  return window['go']['main']['App']['WindowMinimize']();
}
