// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConnectToDatabase(arg1) {
  return window['go']['main']['App']['ConnectToDatabase'](arg1);
}

export function DeleteConnection(arg1) {
  return window['go']['main']['App']['DeleteConnection'](arg1);
}

export function DisconnectFromDatabase(arg1) {
  return window['go']['main']['App']['DisconnectFromDatabase'](arg1);
}

export function ExecuteNonQuery(arg1, arg2, arg3) {
  return window['go']['main']['App']['ExecuteNonQuery'](arg1, arg2, arg3);
}

export function ExecuteQuery(arg1, arg2, arg3) {
  return window['go']['main']['App']['ExecuteQuery'](arg1, arg2, arg3);
}

export function GetConnections() {
  return window['go']['main']['App']['GetConnections']();
}

export function GetDatabases(arg1) {
  return window['go']['main']['App']['GetDatabases'](arg1);
}

export function GetFunctions(arg1, arg2) {
  return window['go']['main']['App']['GetFunctions'](arg1, arg2);
}

export function GetLanguage() {
  return window['go']['main']['App']['GetLanguage']();
}

export function GetServerInfo(arg1) {
  return window['go']['main']['App']['GetServerInfo'](arg1);
}

export function GetSupportedDatabases() {
  return window['go']['main']['App']['GetSupportedDatabases']();
}

export function GetSupportedFeatures() {
  return window['go']['main']['App']['GetSupportedFeatures']();
}

export function GetTableColumns(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetTableColumns'](arg1, arg2, arg3);
}

export function GetTableForeignKeys(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetTableForeignKeys'](arg1, arg2, arg3);
}

export function GetTableIndexes(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetTableIndexes'](arg1, arg2, arg3);
}

export function GetTableStats(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetTableStats'](arg1, arg2, arg3);
}

export function GetTables(arg1, arg2) {
  return window['go']['main']['App']['GetTables'](arg1, arg2);
}

export function GetViews(arg1, arg2) {
  return window['go']['main']['App']['GetViews'](arg1, arg2);
}

export function OpenFileDialog(arg1, arg2) {
  return window['go']['main']['App']['OpenFileDialog'](arg1, arg2);
}

export function RunAllTests() {
  return window['go']['main']['App']['RunAllTests']();
}

export function RunConnectionTest(arg1) {
  return window['go']['main']['App']['RunConnectionTest'](arg1);
}

export function SaveConnection(arg1) {
  return window['go']['main']['App']['SaveConnection'](arg1);
}

export function SaveFileDialog(arg1, arg2) {
  return window['go']['main']['App']['SaveFileDialog'](arg1, arg2);
}

export function SetLanguage(arg1) {
  return window['go']['main']['App']['SetLanguage'](arg1);
}

export function TestConnection(arg1) {
  return window['go']['main']['App']['TestConnection'](arg1);
}

export function WindowClose() {
  return window['go']['main']['App']['WindowClose']();
}

export function WindowIsMaximized() {
  return window['go']['main']['App']['WindowIsMaximized']();
}

export function WindowMaximize() {
  return window['go']['main']['App']['WindowMaximize']();
}

export function WindowMinimize() {
  return window['go']['main']['App']['WindowMinimize']();
}
